export const homeObjOne = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: " tech to serve people",
  headline: "We make innovative WEBSITES and beyond",
  description: "Adapts applications to a standardized process",
  buttonLabel: "Discover it",
  imgStart: "",
  img: require("/standards/static/media/svg-2.svg"),
  alt: "Web Page",
  linkTo: "./service",
  buttonSize: "btn--wide",
  buttonColor: "yellow",
};
export const homeObjTwo = {
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "build your digital products with us",
  headline: "Web Development according to your business needs",
  description: "Homepages, magazine, portfolio, blogs, online booking & more",
  buttonLabel: "Contact Us",
  imgStart: "start",
  img: "/standards/static/media/svg-2.svg",
  alt: "Vaut",
  linkTo: "./contacts",
  buttonSize: "btn--wide",
  buttonColor: "yellow",
};

export const homeObjThree = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "integrated accounting",
  headline: "eCommerce with integration platform updated 24/7",
  description:
    "Sync Odoo transactions automatically track sales, expenses, deposits, and payments",
  buttonLabel: "Learn More",
  imgStart: "",
  img: require("../../images/svg-3.svg"),
  alt: "Vfult",
  linkTo: "./service",
  buttonSize: "btn--wide",
  buttonColor: "yellow",
};

export const homeObjFour = {
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "tired to wait for the accurate profit?",
  headline: "Standards Apps let you know the exact profit in real-time",
  description:
    "Manage sales, projects, manufacturing, POS, inventory, accounting, HR, marketing, and more into a single software solution.",
  buttonLabel: "meets Odoo",
  imgStart: "start",
  img: "https://bitstandard.github.io/standards/static/media/svg-3.svg",
  alt: "Vaddult",
  linkTo: "./odoo",
  buttonSize: "btn--wide",
  buttonColor: "yellow",
};

export const homeObjFive = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "have a special request?",
  headline: "Let's know your needs",
  description: "We will likely give you a hand",
  buttonLabel: "Contact Us",
  imgStart: "",
  img: require("/standards/static/media/svg-3.svg"),
  alt: "Vault",
  linkTo: "./contacts",
  buttonSize: "btn--wide",
  buttonColor: "yellow",
};
